name: Release
run-name: Release on ${{ github.ref }} branch

on:
  workflow_dispatch:
    inputs:
      github-ref:
        required: true
        type: string
        default: 'main'
        description: Ref to build
      version:
        required: true
        type: string
        description: Version to release
      dry-run:
        type: boolean
        description: Dry run
      skip-changelog-update:
        type: boolean
        description: Skip changelog update

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.github-ref || github.sha }}

      - name: Configure GIT identity
        run: |
          git config --global user.email "bitdevops@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Install dependencies
        uses: ./.github/actions/installDependencies

      - name: Build
        run: npm run build

      - name: Release to NPM
        run: npm run release
        env:
          VERSION: ${{ inputs.version }}
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          DRY_RUN: ${{ inputs.dry-run }}
          SKIP_CHANGELOG_UPDATE: ${{ inputs.skip-changelog-update }}
